# Generated by Django 2.2.1 on 2019-05-23 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.CharField(db_index=True, default='Avhi', max_length=50),
        ),
    ]
