# Generated by Django 2.2.1 on 2019-05-23 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='publisher',
            field=models.CharField(db_index=True, default='Publisher_Name', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='author',
            field=models.CharField(db_index=True, default='Author_Name', max_length=50),
        ),
    ]
