# Generated by Django 2.2.1 on 2019-06-23 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20190622_1818'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
